name: Java CI with Maven

on:
  push:
    branches:
      - main
      - ci/45-add-ci-into-framework

jobs:
  Clean:
    name: Clean Project
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Set up Java 17"
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: "Clean Maven Project"
        run: mvn clean

  Test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Set up Java 17"
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: "Run Maven Tests"
        run: mvn test

  Execute:
    name: Execute Main Class
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Set up Java 17"
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: "Execute Main Class"
        run: mvn exec:java -Dexec.mainClass=decide.application.DeciderApplication

  Package:
    name: Package and run JAR
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Set up Java 17"
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: "Package with Maven"
        run: mvn clean package

      - name: "Generate JAR Filename"
        id: jar-info
        run: |
          ARTIFACT_ID=$(mvn help:evaluate -Dexpression=artifactId -q -DforceStdout)
          VERSION=$(mvn help:evaluate -Dexpression=version -q -DforceStdout)
          JAR_NAME="${ARTIFACT_ID}-${VERSION}.jar"
          echo "JAR_NAME=$JAR_NAME" >> $GITHUB_ENV

      - name: "Run JAR"
        run: |
          java -jar target/$JAR_NAME